name: HQPersonalChest
version: 1.0
api-version: 1.13
main: kr.hqservice.chest.HQPersonalChest
authors: [ Cosine_A ]
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:1.8.0
softdepend:
  - MS-Core

commands:
  창고:
    description: 창고 관련 명령어입니다.
  창고관리:
    permission: op
    description: 창고 관리 관련 명령어입니다.